# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1028)),
                ('summary', models.CharField(max_length=15000)),
                ('year', models.IntegerField(max_length=11)),
                ('pubmed_id', models.IntegerField(max_length=11)),
                ('journal', models.CharField(max_length=512)),
                ('pubmed_central_id', models.IntegerField(max_length=11)),
            ],
        ),
    ]
