# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_id',
            field=models.CharField(default='DEFAULT VALUE', max_length=64),
        ),
    ]
